baseURL = 'https://ecole-francaise.nz/'
languageCode = 'en-nz'
title = 'Auckland French International School'
author = 'EFIA'

defaultContentLanguage = "en"
enableRobotsTXT = true

[languages]
[languages.en]
title = "Auckland French International School"
weight = 1
contentDir = "content/en"
[languages.en.params]
flag = "🇳🇿"
description = "Auckland French International School"

[languages.fr]
title = "École Française Internationale Auckland"
weight = 2
contentDir = "content/fr"
[languages.fr.params]
flag = "🇫🇷"
description = "École Française Internationale Auckland"


[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
logo = "/images/efia-logo4.png"
copyrightYears = 2024
themeColor = "blue"
bannerHeight = "200px"

[social]
twitter = "afauckland"
